version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  web:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
